In [1]:
#Download Dataset
!wget https://dibbs.ai.arizona.edu/dibbs/azsecure-forums-darkweb/IslamicNetwork.zip

--2022-09-06 19:31:23--  https://dibbs.ai.arizona.edu/dibbs/azsecure-forums-darkweb/IslamicNetwork.zip
Resolving dibbs.ai.arizona.edu (dibbs.ai.arizona.edu)... 150.135.51.222
Connecting to dibbs.ai.arizona.edu (dibbs.ai.arizona.edu)|150.135.51.222|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27131432 (26M) [application/x-zip-compressed]
Saving to: ‘IslamicNetwork.zip’

IslamicNetwork.zip  100%[===================>]  25.87M  2.18MB/s    in 13s

2022-09-06 19:31:39 (1.94 MB/s) - ‘IslamicNetwork.zip’ saved [27131432/27131432]

In [3]:
#unzip file
!unzip IslamicNetwork.zip

Archive:  IslamicNetwork.zip
  inflating: IslamicNetwork.txt
  inflating: README-ISLAMICNETWORK.txt

In [5]:
import pandas as pd
df = pd.read_fwf('IslamicNetwork.txt')
df.to_csv('IslamicNetwork.csv')

In [ ]:
df = pd.read_csv('IslamicNetwork.csv',index=False)

/tmp/ipykernel_7072/3890108154.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('prova.csv')

,Unnamed: 0,MessageID\tThreadID\tThreadName\tMemberID\tMemberName\tMessage\tP_Year\tP_Month\tP_Day\tP_Date\tThreadFirstMessageID,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 340,Unnamed: 341,Unnamed: 342,Unnamed: 343,Unnamed: 344,Unnamed: 345,Unnamed: 346,Unnamed: 347,Unnamed: 348,Unnamed: 349
0,0,10\t10\ttest00\tdot\tdot\ttttttttttttt\t2004\t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,100\t37\tSpeaking Without Knowledge\tArwa\tArw...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1000\t240\tMusic in Islam\tMoustafa\tMoustafa\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,10000\t200\tStart From Scratch\tKeeping Faith\...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,100001\t10742\tTo Be A Mother\tahm\tahm\tI lik...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_new = df.loc[df['MemberName'].isin(['AbuIlyaas', 'Editor', 'Helper', 'Isam Rajab', 'Khadijah~UmmZakariyyah', 'Prof', 'Rose15', 'caramel', 'heartsofgreenbirds', 'sasjamal'])]

df.to_csv('IslamicNetwork_10_user.csv',index=False)